name: Compilación Automática .NET (CI)

on:
  push:
    branches: [ "main", "staging", "develop" ]
  pull_request:
    branches: [ "main", "staging", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.308
        
    - name: Restore dependencies
      run: dotnet restore TaskManagerSolution.sln
      
    - name: Build
      run: dotnet build TaskManagerSolution.sln --no-restore --configuration Release
